# Project - 2 Data Cleaner

# Part - A Handling Missing Value

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("healthcare_patient_dataset.csv")
df

,patient_id,age,gender,region,bmi,blood_pressure,cholesterol,glucose,disease_risk
0,P10001,24.0,Female,East,23.1,102.2,192.2,136.7,0
1,P10002,73.0,Female,South,31.8,101.2,181.2,120.9,0
2,P10003,65.0,Male,North,27.2,95.7,220.5,105.4,1
3,P10004,49.0,Male,South,25.5,125.8,55.0,93.9,1
4,P10005,49.0,Male,East,26.4,142.0,185.2,94.6,0
...,...,...,...,...,...,...,...,...,...
495,P10496,47.0,Male,North,22.6,119.7,190.1,112.3,0
496,P10497,26.0,Male,East,29.4,120.2,157.0,87.3,1
497,P10498,44.0,Male,West,32.1,112.2,NaN,420.0,1
498,P10499,84.0,Female,South,27.2,131.8,170.2,66.6,1
499,P10500,48.0,Female,South,20.3,127.8,55.0,138.8,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   patient_id      500 non-null    object
 1   age             482 non-null    float64
 2   gender          486 non-null    object
 3   region          484 non-null    object
 4   bmi             472 non-null    float64
 5   blood_pressure  476 non-null    float64
 6   cholesterol     475 non-null    float64
 7   glucose         474 non-null    float64
 8   disease_risk    500 non-null    int64
dtypes: float64(5), int64(1), object(3)
memory usage: 35.3+ KB

In [60]:
df["age"]

0      24.0
1      73.0
2      65.0
3      49.0
4      49.0
       ...
495    47.0
496    26.0
497    44.0
498    84.0
499    48.0
Name: age, Length: 500, dtype: float64

In [62]:
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

print(df.isnull().sum())

patient_id        0
age               0
gender            0
region            0
bmi               0
blood_pressure    0
cholesterol       0
glucose           0
disease_risk      0
dtype: int64

In [63]:
df["bmi"]

0      23.1
1      31.8
2      27.2
3      25.5
4      26.4
       ...
495    22.6
496    29.4
497    32.1
498    27.2
499    20.3
Name: bmi, Length: 500, dtype: float64

# 1. Identify Missing Value Report

In [64]:
missing_report = pd.DataFrame({
    "missing count": df.isnull().sum(),
    "missing percentage" :(df.isnull().sum()/len(df)*100).round(2),
    "Data Type" : df.dtypes.astype(str)
})
print("missing Value Reports: ")
print(missing_report)

missing Value Reports:
                missing count  missing percentage Data Type
patient_id                  0                 0.0    object
age                         0                 0.0   float64
gender                      0                 0.0    object
region                      0                 0.0    object
bmi                         0                 0.0   float64
blood_pressure              0                 0.0   float64
cholesterol                 0                 0.0   float64
glucose                     0                 0.0   float64
disease_risk                0                 0.0     int64

# 2. Simple Imputer

In [65]:
from sklearn.impute import SimpleImputer

In [66]:
df_simple = df.copy()

In [67]:
df_simple = df.copy()

df_simple["bmi"] = SimpleImputer(strategy="median").fit_transform(
    df_simple[["bmi"]]
)
df_simple

,patient_id,age,gender,region,bmi,blood_pressure,cholesterol,glucose,disease_risk
0,P10001,24.0,Female,East,23.1,102.2,192.200000,136.7,0
1,P10002,73.0,Female,South,31.8,101.2,181.200000,120.9,0
2,P10003,65.0,Male,North,27.2,95.7,220.500000,105.4,1
3,P10004,49.0,Male,South,25.5,125.8,55.000000,93.9,1
4,P10005,49.0,Male,East,26.4,142.0,185.200000,94.6,0
...,...,...,...,...,...,...,...,...,...
495,P10496,47.0,Male,North,22.6,119.7,190.100000,112.3,0
496,P10497,26.0,Male,East,29.4,120.2,157.000000,87.3,1
497,P10498,44.0,Male,West,32.1,112.2,196.370947,420.0,1
498,P10499,84.0,Female,South,27.2,131.8,170.200000,66.6,1
499,P10500,48.0,Female,South,20.3,127.8,55.000000,138.8,0

# 3. Simple Imputer(Category)

In [68]:
df_random = df.copy()

cols = ["age", "gender", "region", "bmi",
        "blood_pressure", "cholesterol", "glucose"]

for col in cols:
    df_random[col + "_missing"] = df_random[col].isnull().astype(int)
    mask = df_random[col].isnull()
    values = df_random[col].dropna()

In [69]:
    if mask.sum() > 0 and len(values) > 0:
        df_random.loc[mask, col] = np.random.choice(
            values, size=mask.sum(), replace=True
        )

In [70]:
print("Missing Indicator + Random Sample Imputation")
display(df_random.head())

print("Remaining Missing Values:")
print(df_random[cols].isnull().sum())

Missing Indicator + Random Sample Imputation

,patient_id,age,gender,region,bmi,blood_pressure,cholesterol,glucose,disease_risk,age_missing,gender_missing,region_missing,bmi_missing,blood_pressure_missing,cholesterol_missing,glucose_missing
0,P10001,24.0,Female,East,23.1,102.2,192.2,136.7,0,0,0,0,0,0,0,0
1,P10002,73.0,Female,South,31.8,101.2,181.2,120.9,0,0,0,0,0,0,0,0
2,P10003,65.0,Male,North,27.2,95.7,220.5,105.4,1,0,0,0,0,0,0,0
3,P10004,49.0,Male,South,25.5,125.8,55.0,93.9,1,0,0,0,0,0,0,0
4,P10005,49.0,Male,East,26.4,142.0,185.2,94.6,0,0,0,0,0,0,0,0

Remaining Missing Values:
age               0
gender            0
region            0
bmi               0
blood_pressure    0
cholesterol       0
glucose           0
dtype: int64

# 4. KNN Imputer

In [71]:
from sklearn.impute import KNNImputer

In [72]:
df_knn = df.copy()
cols = ["age", "bmi", "blood_pressure", "cholesterol", "glucose"]

imputer = KNNImputer(n_neighbors=5)
df_knn[cols] = imputer.fit_transform(df_knn[cols])

df_knn.head()

,patient_id,age,gender,region,bmi,blood_pressure,cholesterol,glucose,disease_risk
0,P10001,24.0,Female,East,23.1,102.2,192.2,136.7,0
1,P10002,73.0,Female,South,31.8,101.2,181.2,120.9,0
2,P10003,65.0,Male,North,27.2,95.7,220.5,105.4,1
3,P10004,49.0,Male,South,25.5,125.8,55.0,93.9,1
4,P10005,49.0,Male,East,26.4,142.0,185.2,94.6,0

# 5. MICE Algorithm

In [73]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [74]:
df_MICE = df.copy()

cols = ["age", "bmi", "blood_pressure", "cholesterol", "glucose"]
imputer = IterativeImputer(max_iter = 10 ,random_state=42)
df_MICE[cols] = imputer.fit_transform(df_MICE[cols])

In [75]:
df_MICE.head()

,patient_id,age,gender,region,bmi,blood_pressure,cholesterol,glucose,disease_risk
0,P10001,24.0,Female,East,23.1,102.2,192.2,136.7,0
1,P10002,73.0,Female,South,31.8,101.2,181.2,120.9,0
2,P10003,65.0,Male,North,27.2,95.7,220.5,105.4,1
3,P10004,49.0,Male,South,25.5,125.8,55.0,93.9,1
4,P10005,49.0,Male,East,26.4,142.0,185.2,94.6,0

# Part - B Handling Outliers

In [76]:
df_outlier = df.copy()

In [77]:
df.head()

,patient_id,age,gender,region,bmi,blood_pressure,cholesterol,glucose,disease_risk
0,P10001,24.0,Female,East,23.1,102.2,192.2,136.7,0
1,P10002,73.0,Female,South,31.8,101.2,181.2,120.9,0
2,P10003,65.0,Male,North,27.2,95.7,220.5,105.4,1
3,P10004,49.0,Male,South,25.5,125.8,55.0,93.9,1
4,P10005,49.0,Male,East,26.4,142.0,185.2,94.6,0

In [78]:
df_outlier = df.copy()

print("Original Shape:", df_outlier.shape)
display(df_outlier[["bmi", "cholesterol", "glucose"]].describe())

Original Shape: (500, 9)

              bmi  cholesterol     glucose
count  500.000000   500.000000  500.000000
mean    27.437288   196.370947  110.464768
std      6.290341    44.407063   39.235283
min      8.500000    55.000000   35.000000
25%     24.100000   175.250000   90.975000
50%     27.437288   196.370947  107.700000
75%     30.400000   214.550000  123.150000
max     62.300000   510.000000  420.000000

# 2. Z-Score Method

In [79]:
from scipy.stats import zscore

In [80]:
z = df_outlier[["cholesterol", "glucose"]].apply(zscore)

df_zscore = df_outlier[(z.abs() <= 3).all(axis=1)]

print("After Z-score:", df_zscore.shape)

After Z-score: (480, 9)

# 3. IQR Method

In [81]:
Q1 = df_outlier["bmi"].quantile(0.25)
Q3 = df_outlier["bmi"].quantile(0.75)

IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
Upper = Q3 + 1.5 * IQR

df_IQR = df_outlier[
    (df_outlier["bmi"] >= lower) &
    (df_outlier["bmi"] <= Upper)
    ]
print(df_IQR)

    patient_id   age  gender region   bmi  blood_pressure  cholesterol  \
0       P10001  24.0  Female   East  23.1           102.2   192.200000
1       P10002  73.0  Female  South  31.8           101.2   181.200000
2       P10003  65.0    Male  North  27.2            95.7   220.500000
3       P10004  49.0    Male  South  25.5           125.8    55.000000
4       P10005  49.0    Male   East  26.4           142.0   185.200000
..         ...   ...     ...    ...   ...             ...          ...
495     P10496  47.0    Male  North  22.6           119.7   190.100000
496     P10497  26.0    Male   East  29.4           120.2   157.000000
497     P10498  44.0    Male   West  32.1           112.2   196.370947
498     P10499  84.0  Female  South  27.2           131.8   170.200000
499     P10500  48.0  Female  South  20.3           127.8    55.000000

     glucose  disease_risk
0      136.7             0
1      120.9             0
2      105.4             1
3       93.9             1
4       94.6             0
..       ...           ...
495    112.3             0
496     87.3             1
497    420.0             1
498     66.6             1
499    138.8             0

[487 rows x 9 columns]

# 4. Percentile Method

In [82]:
df_percentile = df_outlier.copy()

for col in ["bmi", "cholesterol", "glucose"]:
    low = df_percentile[col].quantile(0.01)
    high = df_percentile[col].quantile(0.99)

    df_percentile[col] = df_percentile[col].clip(low, high)
    
df_percentile.head()

,patient_id,age,gender,region,bmi,blood_pressure,cholesterol,glucose,disease_risk
0,P10001,24.0,Female,East,23.1,102.2,192.2,136.7,0
1,P10002,73.0,Female,South,31.8,101.2,181.2,120.9,0
2,P10003,65.0,Male,North,27.2,95.7,220.5,105.4,1
3,P10004,49.0,Male,South,25.5,125.8,64.9,93.9,1
4,P10005,49.0,Male,East,26.4,142.0,185.2,94.6,0

# 5. Winsorization

In [83]:
from scipy.stats.mstats import winsorize

In [84]:
df_winsor = df_outlier.copy()

for col in ["bmi", "cholesterol", "glucose"]:
    df_winsor[col] = winsorize(
        df_winsor[col], limits=[0.01, 0.01]
    )

In [85]:
df_winsor.head()

,patient_id,age,gender,region,bmi,blood_pressure,cholesterol,glucose,disease_risk
0,P10001,24.0,Female,East,23.1,102.2,192.2,136.7,0
1,P10002,73.0,Female,South,31.8,101.2,181.2,120.9,0
2,P10003,65.0,Male,North,27.2,95.7,220.5,105.4,1
3,P10004,49.0,Male,South,25.5,125.8,65.0,93.9,1
4,P10005,49.0,Male,East,26.4,142.0,185.2,94.6,0

# 6. Before and After

In [86]:
print("Original Shape:", df_outlier.shape)
print("Z-score Shape:", df_zscore.shape)
print("IQR Shape:", df_IQR.shape)
print("Percentile Shape:", df_percentile.shape)
print("Winsorization Shape:", df_winsor.shape)

print("\nOriginal Summary:")
display(df_outlier[["bmi", "cholesterol", "glucose"]].describe())

print("\nAfter Winsorization:")
display(df_winsor[["bmi", "cholesterol", "glucose"]].describe())

Original Shape: (500, 9)
Z-score Shape: (480, 9)
IQR Shape: (487, 9)
Percentile Shape: (500, 9)
Winsorization Shape: (500, 9)

Original Summary:

              bmi  cholesterol     glucose
count  500.000000   500.000000  500.000000
mean    27.437288   196.370947  110.464768
std      6.290341    44.407063   39.235283
min      8.500000    55.000000   35.000000
25%     24.100000   175.250000   90.975000
50%     27.437288   196.370947  107.700000
75%     30.400000   214.550000  123.150000
max     62.300000   510.000000  420.000000

After Winsorization:

              bmi  cholesterol     glucose
count  500.000000   500.000000  500.000000
mean    27.470288   195.830947  109.684768
std      5.983451    40.396734   33.469175
min     15.000000    65.000000   60.000000
25%     24.100000   175.250000   90.975000
50%     27.437288   196.370947  107.700000
75%     30.400000   214.550000  123.150000
max     55.000000   390.000000  290.000000

In [87]:
df

,patient_id,age,gender,region,bmi,blood_pressure,cholesterol,glucose,disease_risk
0,P10001,24.0,Female,East,23.1,102.2,192.200000,136.7,0
1,P10002,73.0,Female,South,31.8,101.2,181.200000,120.9,0
2,P10003,65.0,Male,North,27.2,95.7,220.500000,105.4,1
3,P10004,49.0,Male,South,25.5,125.8,55.000000,93.9,1
4,P10005,49.0,Male,East,26.4,142.0,185.200000,94.6,0
...,...,...,...,...,...,...,...,...,...
495,P10496,47.0,Male,North,22.6,119.7,190.100000,112.3,0
496,P10497,26.0,Male,East,29.4,120.2,157.000000,87.3,1
497,P10498,44.0,Male,West,32.1,112.2,196.370947,420.0,1
498,P10499,84.0,Female,South,27.2,131.8,170.200000,66.6,1
499,P10500,48.0,Female,South,20.3,127.8,55.000000,138.8,0

# Part - C Final Clean Dataset

In [90]:
from scipy.stats.mstats import winsorize

In [91]:
df_clean = df.copy()

num_cols = df_clean.select_dtypes(include="number").columns
df_clean[num_cols] = df_clean[num_cols].fillna(
    df_clean[num_cols].mean()
)

In [92]:
cat_cols = df_clean.select_dtypes(include="object").columns

for col in cat_cols:
    if df_clean[col].isnull().any():
        df_clean[col] = df_clean[col].fillna(
            df_clean[col].mode()[0]
        )

In [95]:
for col in ["bmi", "cholesterol", "glucose"]:
    df_clean[col] = winsorize(
        df_clean[col], limits=[0.01, 0.01]
    )
    
print("Dataset Shape:", df_clean.shape)
print("Remaining Null Values:", df_clean.isnull().sum().sum())
display(df_clean.head())

Dataset Shape: (500, 9)
Remaining Null Values: 0

,patient_id,age,gender,region,bmi,blood_pressure,cholesterol,glucose,disease_risk
0,P10001,24.0,Female,East,23.1,102.2,192.2,136.7,0
1,P10002,73.0,Female,South,31.8,101.2,181.2,120.9,0
2,P10003,65.0,Male,North,27.2,95.7,220.5,105.4,1
3,P10004,49.0,Male,South,25.5,125.8,65.0,93.9,1
4,P10005,49.0,Male,East,26.4,142.0,185.2,94.6,0

In [96]:
df_clean.to_csv("final_cleaned_dataset.csv", index=False)

In [97]:
df

,patient_id,age,gender,region,bmi,blood_pressure,cholesterol,glucose,disease_risk
0,P10001,24.0,Female,East,23.1,102.2,192.200000,136.7,0
1,P10002,73.0,Female,South,31.8,101.2,181.200000,120.9,0
2,P10003,65.0,Male,North,27.2,95.7,220.500000,105.4,1
3,P10004,49.0,Male,South,25.5,125.8,55.000000,93.9,1
4,P10005,49.0,Male,East,26.4,142.0,185.200000,94.6,0
...,...,...,...,...,...,...,...,...,...
495,P10496,47.0,Male,North,22.6,119.7,190.100000,112.3,0
496,P10497,26.0,Male,East,29.4,120.2,157.000000,87.3,1
497,P10498,44.0,Male,West,32.1,112.2,196.370947,420.0,1
498,P10499,84.0,Female,South,27.2,131.8,170.200000,66.6,1
499,P10500,48.0,Female,South,20.3,127.8,55.000000,138.8,0